name: Run Data Pipeline

on:
 push:
  branches:
   - main

jobs:
 run-project:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout Repository
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: "3.10"

  - name: Install Libraries
    run: |
      pip install pandas

  - name: Run script
    run: |
      python <<EOF
      import pandas as pd
      import sqlite3

      df = pd.read_csv("sentimentdataset_clean.csv")

      conn = sqlite3.connect("data.db")
      df.to_sql("sentiment", conn, if_exists="replace", index=False)

      query = "SELECT sentiment, COUNT(*) as count FROM sentiment GROUP BY sentiment"
      result = pd.read_sql(query, conn)

      result.to_csv("output_summary.csv", index=False)

      print("Success")
      EOF

